# Generated by Django 5.0.6 on 2025-04-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_otp_customuser_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='home_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_deviation_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_return_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
