# Generated by Django 5.2 on 2025-04-04 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_riderequest_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
